// <auto-generated />
namespace DigitalMarket.Db.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201603161401058_Add_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
